// ──────────────────────────────────────────────
// PawPets — Database Seed
// ──────────────────────────────────────────────
// Idempotent seed: admin user (upsert) + 7
// categories with subcategories (createMany).
// ──────────────────────────────────────────────

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Placeholder bcrypt hash for "Admin123!" (cost 10).
// Replace with a proper hash generated by bcrypt in production.
const ADMIN_PASSWORD_HASH =
  "$2b$10$abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123";

// ── Seed data ─────────────────────────────────

const SEED_CATEGORIES = [
  {
    name: "Perros",
    slug: "perros",
    description: "Todo para tu perro",
    subcategories: [
      { name: "Alimentos Balanceados", slug: "alimentos-balanceados" },
      { name: "Snacks y Premios", slug: "snacks-y-premios" },
      { name: "Juguetes", slug: "juguetes" },
      { name: "Camas y Mantas", slug: "camas-y-mantas" },
      { name: "Correas y Collares", slug: "correas-y-collares" },
    ],
  },
  {
    name: "Gatos",
    slug: "gatos",
    description: "Todo para tu gato",
    subcategories: [
      { name: "Alimentos Balanceados", slug: "alimentos-balanceados" },
      { name: "Snacks y Premios", slug: "snacks-y-premios" },
      { name: "Juguetes", slug: "juguetes" },
      { name: "Camas y Rascadores", slug: "camas-y-rascadores" },
      { name: "Areneros y Accesorios", slug: "areneros-y-accesorios" },
    ],
  },
  {
    name: "Aves",
    slug: "aves",
    description: "Todo para tus aves",
    subcategories: [
      { name: "Alimentos", slug: "alimentos" },
      { name: "Jaulas y Accesorios", slug: "jaulas-y-accesorios" },
      { name: "Juguetes", slug: "juguetes" },
    ],
  },
  {
    name: "Peces",
    slug: "peces",
    description: "Todo para tu acuario",
    subcategories: [
      { name: "Acuarios y Peceras", slug: "acuarios-y-peceras" },
      { name: "Alimentos", slug: "alimentos" },
      { name: "Filtros y Accesorios", slug: "filtros-y-accesorios" },
    ],
  },
  {
    name: "Roedores",
    slug: "roedores",
    description: "Todo para tus roedores",
    subcategories: [
      { name: "Alimentos", slug: "alimentos" },
      { name: "Jaulas y Hábitats", slug: "jaulas-y-habitats" },
      { name: "Accesorios", slug: "accesorios" },
    ],
  },
  {
    name: "Salud General",
    slug: "salud-general",
    description: "Medicamentos y cuidado para mascotas",
    subcategories: [
      { name: "Medicamentos", slug: "medicamentos" },
      { name: "Higiene y Cuidado", slug: "higiene-y-cuidado" },
      { name: "Suplementos", slug: "suplementos" },
    ],
  },
  {
    name: "Accesorios Generales",
    slug: "accesorios-generales",
    description: "Accesorios para toda mascota",
    subcategories: [
      { name: "Comederos y Bebederos", slug: "comederos-y-bebederos" },
      { name: "Transportadoras", slug: "transportadoras" },
      { name: "Identificacion", slug: "identificacion" },
    ],
  },
] as const;

// ── Main ──────────────────────────────────────

async function main() {
  console.log("🌱 Seeding database...\n");

  // ── Admin user ─────────────────────────────
  const admin = await prisma.user.upsert({
    where: { email: "admin@pawpets.com" },
    update: {},
    create: {
      email: "admin@pawpets.com",
      name: "Admin",
      passwordHash: ADMIN_PASSWORD_HASH,
      role: "ADMIN",
    },
  });
  console.log(`  ✓ Admin user: ${admin.email} (${admin.id})`);

  // ── Categories & Subcategories ─────────────
  let totalSubcategories = 0;

  for (const cat of SEED_CATEGORIES) {
    const category = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { description: cat.description },
      create: {
        name: cat.name,
        slug: cat.slug,
        description: cat.description,
      },
    });

    const { count } = await prisma.subcategory.createMany({
      data: cat.subcategories.map((sub) => ({
        name: sub.name,
        slug: sub.slug,
        categoryId: category.id,
      })),
      skipDuplicates: true,
    });

    totalSubcategories += count;
    console.log(`  ✓ ${cat.name} (${count} subcategories)`);
  }

  console.log(`\n✅ Seed complete.`);
  console.log(`   • 1 admin user`);
  console.log(`   • ${SEED_CATEGORIES.length} categories`);
  console.log(`   • ${totalSubcategories} subcategories`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
